#pragma once

#define	CFG_PATH_RESSOURCE ${PATH_RESSOURCE}
#define	CFG_PATH_SAVE ${PATH_SAVE}
#define	CFG_PATH_PCX_SAVE ${PATH_PCX_SAVE}
#define CFG_PATH_SAVE_BUGS ${PATH_SAVE_BUGS}
#define CFG_DISPLAY_FPS ${DISPLAY_FPS}
#define CFG_FULLSCREEN ${FULLSCREEN}
